site_name: "Cedric's Website"
site_description: "Personal portfolio, blog, and CV built with MkDocs."
theme:
  name: material
  language: en
  logo: assets/perrito-super-gordito.jpeg
  favicon: assets/perrito-super-gordito.jpeg
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: cyan

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: blue

nav:
  - Home: index.md
  - Website Goals: goals.md
  - About: about.md
  - CV: cv.md
  - Comments: comment-section.md
  - Projects:
      - Overview: projects/index.md
      - Project 1: projects/project1.md
  - Blog:
      - Blogs Overview: blog/index.md
      - My Hobbies:
        - Fitness:
           - Fitness Index: blog/my-hobbies/fitness/index.md
        - Climbing:
           - Climbing Index: blog/my-hobbies/climbing/index.md
        - Anime and Manga:
           - Anime and Manga Index: blog/my-hobbies/anime-and-manga/index.md
           - What is Manga/Anime?: blog/my-hobbies/anime-and-manga/what-is-manga-anime.md
        - Music:
           - Music Index: blog/my-hobbies/music/index.md
           - My Favourite Genres: blog/my-hobbies/music/my-favourite-genres.md
        - Programming:
           - Programming Index: blog/my-hobbies/programming/index.md
        - Language Learning:
           - Language Learning Index: blog/my-hobbies/language-learning/index.md
           - Language Starter Guide: blog/my-hobbies/language-learning/starter-guide.md
           - App Review - Tandem: blog/my-hobbies/language-learning/app-review-tandem.md
        - Cooking:
           - Cooking Index: blog/my-hobbies/cooking/index.md
           - Thai Red Curry: blog/my-hobbies/cooking/red-curry.md
      - Miscellaneous:
        - First Post: blog/misc/first-post.md
        - Cheatsheet: blog/misc/cheatsheet.md
  - Contact: contact.md

markdown_extensions:
  - toc
  - tables
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  
extra_css:
  - stylesheets/comments.css
  - stylesheets/cv.css